[platformio]
; Hier wählst Du das aktive Board aus (aktuell der RP2350)
default_envs = daisy_seed
; --- Umgebung 1: Seeed Studio XIAO RP2350 ---
[env:xiao_rp2350]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = seeed_xiao_rp2350
framework = arduino
board_build.core = earlephilhower
; --- Umgebung 2: Electro-Smith Daisy Seed ---
[env:daisy_seed]
platform = ststm32
board = electrosmith_daisy