[platformio]
default_envs = daisy_seed

[env:daisy_seed]
platform = ststm32
board = electrosmith_daisy
framework = stm32cube
lib_ldf_mode = deep

board_build.mcu = stm32h750ibk6
board_build.f_cpu = 400000000L
board_build.ldscript = lib/libDaisy/core/STM32H750IB_flash.lds
board_build.stm32cube.custom_config_header = yes

upload_protocol = dfu

platform_packages =
    platformio/toolchain-gccarmnoneeabi@~1.120301.0

extra_scripts = supplimental_linker_script.py

build_flags =
    -D USBCON
    -D FILEIO_ENABLE_FATFS_READER
    -mthumb
    -mfloat-abi=hard
    -mfpu=fpv5-d16
    -mcpu=cortex-m7
    -D USE_HAL_DRIVER
    -D USE_FULL_LL_DRIVER
    -D STM32H750xx
    -I lib/libDaisy/src
    -I lib/libDaisy/src/sys
    -I lib/libDaisy/src/usbh
    -I lib/libDaisy/core
    -I lib/DaisySP/Source
    -I lib/DaisySP/Source/Utility

build_unflags =
    -mfpu=fpv4-sp-d16
